### ISSUE TITLE
please remove the components that track me. I can't download the app because of them, others can't either.

### ISSUE THREAD

**Issue by Wjxfi** [vishal2376/git-coach#3] opened 2023-06-22 11:58 UTC
I am 100% sure that with these components the app will not become popular

delete them please

Anti-Features:
ApplicationDebuggable: APK files of this application are compiled for debugging („application-debuggable“). For details, see e.g. What are the security implications of using an app built “for debug”.
NonFreeDep (the application depends on a non-free application):
⇒ contains libraries of Google Mobile Services and Google Play Core
NonFreeNet (this application promotes/depends a non-Free network service):
⇒ connects to Google services (Play Store)

**Comment by vishal2376** [comment] 2023-06-22 12:59
Thank you for your concern about tracking components in our app. Here are some clarifications:

- App's entire code is open source for transparency.
- The Play Store is used solely for in-app updates, not for tracking users.
- Connecting to Google services is for app distribution, not for unauthorized data collection.
- This App does require any permissions like internet, storage, etc.

If you still think that app is tracking data then show me proof, entire code is open source.

**Comment by Wjxfi** [comment] 2023-06-22 19:20
Google is absolutely not a trusted company. I can't download apps that have Google. Other many people too, who see these anti-functions.

**Comment by Wjxfi** [comment] 2023-06-22 19:21
Please remove it

**Comment by Wjxfi** [comment] 2023-06-22 19:22
Since this app store is focused on privacy, it is necessary to remove all the bad components. Google doesn't know the word privacy. There are thousands of rumors and facts against Google.

**Comment by vishal2376** [comment] 2023-06-22 19:36
> Google is absolutely not a trusted company. I can't download apps that have Google. Other many people too, who see these anti-functions.

Then why are you using Android OS (developed by Google)

Grow up , stop behaving like small kids.

Build the app yourself.

**Comment by IzzySoft** [comment] 2023-06-29 08:06
@vishal2376 if that isyour stance, I'll hae to remove your app from my repo agin. I just had to disable updates and remove the latest 2 versions as it was overboarding. Do you respect the privacy of other people?

```
Offending libs:
---------------
* Crashlytics (/com/crashlytics): NonFreeDep,Tracking
* Google Ads (/com/google/ads): Ads,NonFreeDep
* Firebase Data Transport (/com/google/android/datatransport): NonFreeNet
* Google Mobile Services (/com/google/android/gms): NonFreeDep
* Google Play Core (/com/google/android/play/core): NonFreeNet,NonFreeDep
* Firebase (/com/google/firebase): NonFreeNet,NonFreeDep
* Firebase Analytics (/com/google/firebase/analytics): NonFreeDep,Tracking
* Firebase Installations (/com/google/firebase/installations): NonFreeNet
* Play In-App Updates Library (/com/google/android/play/appupdate): NonFreeDep

9 offenders.
```

> App's entire code is open source for transparency.

Please point us to the source code of Crashlytics, Google Ads, Firebase, GMS etc then.

We'd really appreciate a real FOSS build if you can provide it. If not, please let us know and we'll unable to use your app.

> Then why are you using Android OS (developed by Google)

I use Android developed by the AOSP, not "Google Android". So no Google services, no Playstore etc. I value my privacy.

> Grow up , stop behaving like small kids.

Please don't behave like an ignorant. Accept there are people with different opinions and different needs. We can accept if you like being tracked by BigCorps, and we'll simply ignore your app then without telling you to "grow up" (though we'd appreciate it :wink:)

**Comment by vishal2376** [comment] 2023-06-29 08:35
@IzzySoft Apologies for the inconvenience.

I just want to deliver a bug-free app and keep users updated. To achieve this, I am using two Google services. 

**In-app updates**
It allows me to provide regular app updates with new features and improved performance.

**Crashlytics**
It provides detailed crash and bug reports, enabling me to quickly identify and fix issues

There is a bug that has occurred in Android versions 8 and above, but I have been unable to fix it for the past month because I don't know the root cause.
But after enabling crashlytics , i fix this issue in 2 days.

**_If you have any alternative solutions to the problems then just share it._**

You can also see how this help me to make crash free app 
![image](https://github.com/vishal2376/git-coach/assets/38159691/ef50fc4d-227e-4d09-b13e-32cbcda1ea7b)

**Comment by IzzySoft** [comment] 2023-06-29 12:46
> Apologies for the inconvenience.

Thanks – and accepted :smiley: 

> I just want to deliver a bug-free app and keep users updated.

Which I fully agree is a good idea! Maybe I can recommend you some FOSS and privacy-friendly alternatives to take a look at? I've collected [some candidates here](https://gitlab.com/-/snippets/1896503#acceptable-analytics). I'm aware that Crashlytics/Firebase-Analytics are very convenient, and the alternatives might not "fully match up" to them. But as outlined, at least some of us prefer not to give up privacy for convenience, if possible. Some notes:

* ACRA with "opt-in" crash reporting seems to be very helpful. That's also used by F-Droid. After a crash, ACRA would open a pop-up showing the details to be send allowing the user to transparently see and confirm (which then sends the report) or reject (to not send). Reports can e.g. be sent via mail.
* Sentry can be self-hosted for max privacy, but if you don't have the possibility to self-host you can use their service. Make it opt-in again, so nobody can complain. Here you could have an initial pop-up asking if the user agrees, and have it "toggle-able" from within the app's settings.

Both are fully FOSS, so code can be inspected. I don't know much about the others, so I cannot give advice/details on them.

**Comment by vishal2376** [comment] 2023-07-01 21:29
Remove crashlytics and in-app update dependecies: 996f48990d8a27206660599decb8274887ed817f
Remove in-app update code: 5c57e3c873ca8a0539ca2417c47b5495ec124618

Update will be released in 2-3 days.

**Closed as completed by vishal2376** 2023-07-01 21:29 UTC

**Comment by IzzySoft** [comment] 2023-07-04 23:27
Thanks – new release looks fantastic! I've just pulled it in manually, checked – and then removed all anti-features (white-listing ACRA as it's opt-in). :+1:
